spring:
  application:
    name: water
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/water_clean_db?useTimezone=true&serverTimezone=UTC
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

springdoc:
  pathsToMatch:
    - /auth/**
    - /api/v1/**
  swagger-ui:
    use-root-path: true

security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 14400
logging:
  level:
    com.waterView.water.services.AnalisesService: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

server:
  servlet:
    context-path: /

cors:
  originPatterns: "http://localhost:5173,http://localhost:8080"
